[package]
name = "trnovel"
version = "0.3.0"
edition = "2021"
default-run = "trnovel"
description = "Terminal reader for novel"
authors = ["yexiyue <yexiyue666@qq.com>"]
license = "MIT"
keywords = ["CLI", "Terminal", "Novel", "Reader"]
repository = "https://github.com/yexiyue/TRNovel"

[[bin]]
name = "trnovel"
path = "src/bin/main.rs"

[[bin]]
name = "trn"
path = "src/bin/trn.rs"

[dependencies]
anyhow = "1.0.93"
async-trait = "0.1.83"
chrono = { version = "0.4.38", features = ["serde"] }
clap = { version = "4.5.21", features = ["derive"] }
crossterm = { version = "0.28.1", features = ["event-stream"] }
encoding_rs = { version = "0.8.35", features = ["serde"] }
futures = "0.3.31"
md5 = "0.7.0"
parse-book-source = "0.1.0"
ratatui = { version = "0.29.0", features = ["unstable"] }
regex = "1.11.1"
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"
strum = { version = "0.26.3", features = ["derive"] }
thiserror = "2.0.3"
throbber-widgets-tui = "0.8.0"
tokio = { version = "1.41.1", features = [
    "macros",
    "rt",
    "rt-multi-thread",
    "sync",
    "time",
] }
tokio-util = "0.7.12"
tui-scrollview = "0.5.1"
tui-tree-widget = "0.23.0"
tui-widget-list = "0.13.0"
walkdir = "2.5.0"
